version: '3'
services:
    database:
        image: mariadb:10.3
        command:
            - "--character-set-server=utf8"
            - "--collation-server=utf8_unicode_ci"
        ports:
            - "3307:3306" # (*)
        restart: on-failure:5
        volumes:
            - ./database:/var/lib/mysql
        environment: 
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    wordpress:
        depends_on:
            - database
        image: wordpress:latest
        ports:
            - "9000:80" # (*)
        restart: on-failure:5
        volumes:
            - ./public:/var/www/html
        environment:
            WORDPRESS_DB_HOST: database:3306  # (*)
            WORDPRESS_DB_USER: "${MYSQL_USER}"
            WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
            WORDPRESS_TABLE_PREFIX: "${WP_DB_PREFIX}"
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80 # (*)
        restart: on-failure:5
        environment:
            PMA_HOST: database
            UPLOAD_LIMIT: 1000000000
    wordmove:
        tty: true
        depends_on:
            - wordpress
        build: .
        restart: on-failure:5
        container_name: my_wordmove  # (+)
        volumes:
            - ./config:/home
            - ./public:/var/www/html
            - ~/.ssh:/root/.ssh      # (!)
        env_file: .env

            
#######################################
#
# In case you want to reuse this config 
# for another Wordpress project and 
# them have both run *simultaneously*
# you'll need to:
#
# - change wordmove's container_name
#   to anything else - marked as (+)
#   e.g. wordmove123
#
# - change the first number of ports
#   to another one   - marked as (*)
#   "<new_host_port>:<container_port>"
#   e.g.
#    - change wordpres port numbers 
#      from "8000:80" to "8001:80"
#    - change phmyadmin port numbers 
#      from "8080:80" to "8081:80
#    - change database port numbers 
#      form "3307:3306" to "3308:3306"
#    - change WORDPRESS_DB_HOST port
#      to the new database port
#
# (!) Copy your local .ssh keys only if 
#     necessary to connect to remote
#######################################
